<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="27684" started-at="2018-06-07T17:47:13Z" finished-at="2018-06-07T17:47:41Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="27684" started-at="2018-06-07T17:47:13Z" finished-at="2018-06-07T17:47:41Z">
      <class name="leaf.Lead.EditLead">
        <test-method status="PASS" signature="login(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:leaf.Lead.EditLead@1d422d]" name="login" is-config="true" duration-ms="9528" started-at="2018-06-07T17:47:13Z" finished-at="2018-06-07T17:47:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://leaftaps.com/opentaps]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[DemoSalesManager]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[crmsfa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="editLead()[pri:0, instance:leaf.Lead.EditLead@1d422d]" name="editLead" duration-ms="15952" started-at="2018-06-07T17:47:23Z" finished-at="2018-06-07T17:47:39Z">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at wdMethods.SeMethods.locateElement(SeMethods.java:100)
at leaf.Lead.EditLead.editLead(EditLead.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editLead -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:leaf.Lead.EditLead@1d422d]" name="closeApp" is-config="true" duration-ms="2153" started-at="2018-06-07T17:47:39Z" finished-at="2018-06-07T17:47:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- leaf.Lead.EditLead -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
